// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2181.Cpp2Java;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainMotorFL;
    public static WPI_TalonSRX driveTrainMotorFR;
    public static WPI_TalonSRX driveTrainMotorBL;
    public static WPI_TalonSRX driveTrainMotorBR;
    public static RobotDrive driveTrainmotorControl;
    public static WPI_TalonSRX ropeSpoolSpinnerA;
    public static WPI_TalonSRX ropeSpoolSpinnerB;
    public static DigitalInput gearLoaderEncoder;
    public static DigitalInput gearLoaderLimitSwitch;
    public static SpeedController gearLoaderLandingMotor;
    public static Relay visionHeadlights;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainMotorFL = new WPI_TalonSRX(2);

        
        driveTrainMotorFR = new WPI_TalonSRX(1);

        driveTrainMotorBL = new WPI_TalonSRX(3);

        driveTrainMotorBR = new WPI_TalonSRX(4);

        
        driveTrainmotorControl = new RobotDrive(driveTrainMotorFL, driveTrainMotorBL,
              driveTrainMotorFR, driveTrainMotorBR);
        
        driveTrainmotorControl.setSafetyEnabled(false);
        driveTrainmotorControl.setExpiration(0.1);
        driveTrainmotorControl.setSensitivity(0.5);
        driveTrainmotorControl.setMaxOutput(1.0);

        driveTrainmotorControl.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainmotorControl.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        ropeSpoolSpinnerA = new WPI_TalonSRX(6);

        
        ropeSpoolSpinnerB = new WPI_TalonSRX(5);

        
        gearLoaderEncoder = new DigitalInput(0);

        
        gearLoaderLimitSwitch = new DigitalInput(1);

        
        gearLoaderLandingMotor = new VictorSP(0);

        
        visionHeadlights = new Relay(0);

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
