// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2181.Cpp2Java.subsystems;

import org.usfirst.frc2181.Cpp2Java.RobotMap;
import org.usfirst.frc2181.Cpp2Java.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
	
	private int LIMIT = 1;
	private int DEADZONE_THRESH = 0;
	private int LEFT_X = 0;
	private int LEFT_Y = 1;
	private int RIGHT_X = 4;
	private int RIGHT_Y = 5;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public double deadzone(Joystick j, int axis) {
    	double temp = j.getRawAxis(axis);
    	if (Math.abs(temp) <= DEADZONE_THRESH) {
    		return 0;
    	} else {
    		return temp;
    	}
    }
    
    public void drive(Joystick j) {
    	double x = LIMIT*j.getRawAxis(LEFT_X);
    	double y = LIMIT*j.getRawAxis(LEFT_Y);
    	double z = 0.7*j.getRawAxis(RIGHT_X);
    	
    	//motorControl.mecanumDrive_Cartesian(x, y, z);
    }
    
    public void driveAuto(double x, double y, double rot) {
    	//motorControl.mecanumDrive_Cartesian(x, y, rot);
    }
}

